# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on in this case windows:
    runs-on: [windows-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Import Tenant
      env: 
        ClientId: 2f4c7565-3685-41d5-b92e-cdfcb3b7f2e3
        IdHostName: datagovernor-dev-id.azurewebsites.net
        ApiHostName: datagovernor-dev-api.azurewebsites.net
        AgentHostName: PerDev-DG21.bizdata.local
      shell: pwsh
      run: |
        try {
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $ClientId = $env:ClientId;
        $IdHostName= $env:IdHostName;
            
        $TokenRequestBody = @{
            "grant_type"    = "client_credentials";
            "client_id"     = $ClientId;
            "client_secret" = $ClientId;
            "scope"         = "webApi"
        };
        $AccessToken = ((Invoke-WebRequest -Uri "https://$IdHostName/connect/token" -Method Post -Body $TokenRequestBody).Content | ConvertFrom-Json).access_token;
            
        $ArtifactOutputDir = $env:GITHUB_WORKSPACE;
        $ApiHostName = $env:ApiHost;
        $BaseUrl = "https://$env:ApiHostName/api/v1/";
        $AgentHostname = $env:AgentHostName;
            
        function Upload-Zip ($ZipLocation) {
            $AccessHeaders = @{"Authorization" = "bearer $AccessToken" }
            
            $ZipUploadUrl = $BaseUrl + "Import/Zip?agentHostName=$AgentHostName";
            
            try {
                $Response = Invoke-RestMethod $ZipUploadUrl -Method 'POST' -Headers $AccessHeaders -InFile $ZipLocation -ContentType "application/zip";
                Write-Output $Response;
            }
            catch {
                $Exception = $_.Exception;
                if ($PSVersionTable.PSVersion.Major -lt 6) {
                    if ($Exception.Response) {  
                        $Reader = New-Object System.IO.StreamReader($Exception.Response.GetResponseStream())
                        $Reader.BaseStream.Position = 0
                        $Reader.DiscardBufferedData()
                        $ResponseBody = $Reader.ReadToEnd()
                        if ($ResponseBody.StartsWith('{')) {
                            $ResponseBody = $ResponseBody | ConvertFrom-Json
                        }
                        Write-Output $ResponseBody
                    }
                }
                else {
                    Write-Output $Exception.ErrorDetails.Message
                }
            }
        }
        
        $ZipPath = "tenant.zip";
        Remove-Item $ZipPath -ErrorAction Ignore;
        Get-ChildItem -Recurse -Path $ZipPath | Compress-Archive -DestinationPath $ArtifactOutputDir
        Upload-Zip -ZipLocation $ZipPath;
        Write-Output "Success?"

        }
        catch {
          Write-Output $_.Exception.Message;
        }